# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, ... }:
{

  flake.modules = inputs.self.lib.mkFeature "MAC-QXGYWVX" {
    home =
      { pkgs, ... }:
      {

        services.ssh-agent.enable = !(pkgs.stdenvNoCC.isDarwin);
        programs.fish.shellInit = ''
          fish_add_path $(brew --prefix rustup)/bin
        '';
        programs.ssh = {
          enable = true;
          addKeysToAgent = "yes";
          extraConfig = ''
            Host *
              IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
          '';
        };
      };
    darwin = {
      homebrew = {
        brews = [
          "rustup"
          "protobuf"
          "pipx"
        ];
        casks = [
          "spotify"
        ];
      };
    };
  };
}
